import type { Metadata } from "next";
import { Barlow_Condensed} from "next/font/google";
import "./globals.css";
import Nav from "./components/Navigations/Nav";
import Footer from "./components/Footer/Footer"

const barlow_Condensed = Barlow_Condensed({
  weight: ["300", "500", "600", "400", "700"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Burger ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={barlow_Condensed.className}>
        <Nav />
        {children}
        <Footer />
        </body>
    </html>
  );
}
